version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    ignore:
      # Pin the minor version of Node type definitions so they match the Node
      # release we're using. (Upgrade this package manually together with actual
      # Node version upgrades.)
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    groups:
      npm-minor:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
      eslint:
        patterns:
          - "eslint-*"
          - "*-eslint"
          - "@eslint/*"
      jest:
        patterns:
          - "jest"
          - "ts-jest"
          - "@types/jest"
