name: Deploy
description: Deploys new Lambda function code

inputs:
  aws-role:
    description: AWS role to assume
    required: true
  dry-run:
    description: If truthy, the deploy will be a dry run
    required: false
    default: ""
  environment:
    description: Environment to deploy to (dev/prod)
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup

    - uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-region: us-east-1
        role-to-assume: ${{ inputs.aws-role }}

    - name: Run deploy script
      shell: bash
      run: |
        scripts/deploy.sh \
          ${{ inputs.dry-run && '-d' || '' }} \
          ${{ inputs.environment }}
