name: Deploy To Environment
description: Build docker image and deploy it for each data pipeline.
inputs:
  aws-access-key-id:
    description: AWS_ACCESS_KEY_ID
    required: true
  aws-secret-access-key:
    description: AWS_SECRET_ACCCESS_KEY
    required: true
  env-name:
    description: One of 'prod', 'staging', or 'dev'
    required: true
  slack-webhook-url:
    description: Slack URL to post to
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install Dependencies
      run: npm ci
    - name: Run Tests
      run: npm test
    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: us-east-1 # your AWS region
    - name: Package the Lambda function
      run: |
        zip -r function.zip .
    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code --function-name elevator-hotline-${{ inputs.env-name }} --zip-file fileb://function.zip
    - uses: mbta/actions/notify-slack-deploy@v1
      if: ${{ !cancelled() }}
      with:
        webhook-url: ${{ inputs.slack-webhook-url }}
        job-status: ${{ job.status }}
