name: CI

on:
  push:
    paths-ignore:
      - "*.md"
      - LICENSE

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy dry-run
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/deploy
        with:
          aws-role: ${{ secrets.AWS_ROLE_ARN }}
          dry-run: "true"
          environment: dev

  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: npx --no prettier --check .

  lint:
    name: Check lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: npx --no eslint .

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: |
          source .envrc.template
          npm test

  types:
    name: Check types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: npx --no tsc
