name: CI

on:
  push:
    paths-ignore:
      - "*.md"
      - LICENSE

permissions: {}

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy dry-run
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' && github.ref_name != 'master'
    permissions:
      contents: read # Needed to check out the repository
      id-token: write # Needed to authenticate against AWS
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: $/.github/actions/deploy
        with:
          aws-role: ${{ secrets.AWS_ROLE_ARN }} # zizmor: ignore[secrets-outside-env] - TODO: Move to a dedicated environment
          dry-run: "true"
          environment: dev

  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: $/.github/actions/setup
      - run: npx --no prettier --check .

  lint:
    name: Check lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: $/.github/actions/setup
      - run: npx --no eslint .

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: $/.github/actions/setup
      - run: |
          source .envrc.template
          npm test

  types:
    name: Check types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: $/.github/actions/setup
      - run: npx --no tsc
