name: Deploy

on:
  push:
    branches: ["master"]
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        default: dev

permissions: {}

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed to check out the repository
      id-token: write # Needed to authenticate against AWS
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: $/.github/actions/deploy
        with:
          aws-role: ${{ secrets.AWS_ROLE_ARN }} # zizmor: ignore[secrets-outside-env] - TODO: Move to a dedicated environment
          environment: ${{ inputs.environment || 'dev' }}
