name: Deploy to Dev Environment

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mbta/actions/npm-install@v1
        with:
          node-version: 14
      - uses: mbta/actions/deploy-lambda@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          lambda-function: elevator-hotline-dev
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK }}

