name: Deploy to Dev Environment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mbta/actions/npm-install
      - uses: mbta/actions/deploy-lambda
        with:
          role-to-assume: ${{ secrets.AWS_DEV_ROLE }}
          lambda-function: elevator-hotline-dev
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK }}

